version: '3.9'
services:
  db:
    image: postgres
    restart: unless-stopped
    container_name: db
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      PGDATA: ${PGDATA:-/data/postgres}
    volumes:
      - postgres_post:${PGDATA}
    networks:
      - postgres_post

  dbadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    container_name: dbadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin_post:/root/.pgadmin
    networks:
      - postgres_post

networks:
  postgres_post:
    driver: bridge

volumes:
  postgres_post:
  pgadmin_post: